#define strncpy_s strncpy
#define strncmp_s strncmp

#include "SafeString.h"
#include "EspFunctions.h"

#include "Environment.h"
#include "Profiler.h"
#include "StackWatcher.h"
#include "Instrumentation.h"
#include "InternedStrings.h"
#include "SystemCallback.h"
#include "MyRandom.h"
#include "TimeServices.h"
#include "Delayer.h"
#include "Command.h"
#include "CommandSource.h"
#include "CommandFormatter.h"
#include "ParseErrors.h"
#include "Vector.h"
#include "VariableData.h"
#include "VariableStoreChunk.h"
#include "VariableStore.h"
#include "Variable.h"
#include "VariableCollection.h"
#include "ExpressionResult.h"
#include "LedState.h"
#include "CommandResult.h"
#include "IExecutionFlow.h"
#include "ILedDevice.h"
#include "LedPwmEsp32.h"
#include "LedRGB.h"
#include "ILedDeviceCreator.h"
#include "LedDeviceCreator.h"
#include "LedGroups.h"
#include "LedManager.h"
#include "FunctionStore.h"
#include "Stack.h"
#include "ExpressionNode.h"
#include "CharacterClassifier.h"
#include "ExpressionTokenSource.h"
#include "IButton.h"
#include "IButtonCreator.h"
#include "IExecutionContext.h"
#include "BuiltInFunctions.h"
#include "RDEvaluater.h"
#include "ExecutionContext.h"
#include "ILedMessageHandler.h"
#include "ExecutionFlow.h"
#include "Timebase.h"

#include "TouchButton.h"
#include "ButtonCreator.h"
